# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "*" ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore src/sports-betting-app.sln
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Build
        run: dotnet build src/sports-betting-app.sln 

  test:
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Build
        run: dotnet build src/sports-betting-app.sln
      - name: Test
        run: dotnet test src/sports-betting-app.sln --no-build --verbosity normal
  
